<?php

/**
* Implements hook_cron().
*/

  function mymodule_cron() {
    \Drupal::messenger()->addMessage(t("Hello from mymodule_cron"));
  }

/**
* Implements hook_form_alter().
*/

  function mymodule_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if ($form_id == 'node_article_edit_form') {
      $form['actions']['submit']['#value'] = t("save this article");
    }
  }